---
- debug: 
    msg: "Setting up drupal"

- name: Downloading artifact
  shell: wget https://ftp.drupal.org/files/projects/drupal-8.6.5.zip -P /var/www/html/
- name: installing unzip
  apt:
    name: unzip
    state: present
  
- name: "Extracting to /var/www/html"
  shell: unzip /var/www/html/drupal-8.6.5.zip
  become: true

- name: Setting up file permissions
  shell: |
    mkdir -p /var/www/html/drupal-8.6.5/sites/default/files
    chmod -R 777 /var/www/html/drupal-8.6.5/sites/default/files
    cp /var/www/html/drupal-8.6.5/sites/default/default.settings.php /var/www/html/drupal-8.6.5/sites/default/settings.php
    chmod 777 /var/www/html/drupal-8.6.5/sites/default/settings.php
  become: true
